### ISSUE TITLE
PCB Design & Validation

### ISSUE THREAD

**Issue by Joseph0M** [Joseph0M/DIYson-SolarCycle#6]
# PCB Design

A PCB design is in the works, reducing the reliance on expensive breakouts. The aim is to produce a simple, 2-layer board that can be assembled by JLCPCB or PCBWay. Current timeline looks for a Q2 Release

## To-Do List
- [x] Validate hardware selections, including:
    - VL53L1X ToF Sensor
    - ADPS-9960 Light, Proximity and RGB Sensor
    - DS28E17 I2C Bridge
    - Flick Zero Gesture Sensor
    - Capacitive Buttons or I2C Controlled Buttons
    - RP2040 IC
- [x] Design a custom dual-channel LED driver
- [x] Confirm and validate the Schematic design
    - [x] Independent review
- [ ] Design PCB layout + routing
- [ ] Confirm and validate the PCB design
    - [ ] DRC in line with JLCPCB specifications
    - [ ] Independent review
- [ ] Production
- [ ] Testing
- [ ] Open-Source Release
    - [ ]  Complete documentation and manuals
